/**
 * Self-host the Google Fonts used by the site.
 *
 * Fetches the same families/weights the site previously loaded from
 * fonts.googleapis.com and downloads only the subsets the site actually
 * needs (latin, latin-ext, ethiopic) into public/fonts/, then writes
 * public/fonts/fonts.css with local @font-face blocks.
 *
 * Run: node scripts/fetch-fonts.mjs
 */

import { mkdirSync, writeFileSync, readFileSync, existsSync } from "fs";
import { resolve } from "path";

const ROOT = resolve(import.meta.dirname ?? ".", "..");
const FONT_DIR = resolve(ROOT, "public", "fonts");

const CSS2_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&family=Inter:wght@400;500;600;700&family=Noto+Sans+Ethiopic:wght@400;500;600&display=swap";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

function subsetOf(unicodeRange) {
  if (/U\+1200|U\+2D80|U\+AB01/i.test(unicodeRange)) return "ethiopic";
  if (/U\+0100-024F/i.test(unicodeRange)) return "latin-ext";
  if (/U\+0000-00FF/i.test(unicodeRange)) return "latin";
  return null;
}

function slug(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

mkdirSync(FONT_DIR, { recursive: true });

const cssRes = await fetch(CSS2_URL, { headers: { "user-agent": UA } });
if (!cssRes.ok) throw new Error(`CSS2 fetch failed: ${cssRes.status}`);
const cssText = await cssRes.text();

const blocks = [];
for (const match of cssText.matchAll(/@font-face\s*{([^}]+)}/g)) {
  const body = match[1];
  const field = (name) => {
    const m = body.match(new RegExp(`${name}\\s*:\\s*([^;]+);`));
    return m ? m[1].trim() : undefined;
  };
  const srcUrl = field("src")?.match(/url\((https:[^)]+)\)/)?.[1];
  const unicode = field("unicode-range") ?? "";
  const subset = subsetOf(unicode);
  if (!srcUrl || !subset) continue;
  blocks.push({
    family: field("font-family")?.replace(/['"]/g, ""),
    style: field("font-style"),
    weight: field("font-weight"),
    subset,
    srcUrl,
    unicodeRange: unicode,
  });
}

const seen = new Map();
for (const b of blocks) {
  const key = `${slug(b.family)}-${b.weight}-${b.subset}`;
  if (seen.has(key)) continue; // keep the first block per family/weight/subset
  seen.set(key, b);
}

const localBlocks = [];
for (const b of seen.values()) {
  const file = `${slug(b.family)}-${b.weight}-${b.subset}.woff2`;
  const outPath = resolve(FONT_DIR, file);
  const localHref = `/fonts/${file}`;
  console.log(`↓ ${file} (${b.style || "normal"} ${b.weight}, ${b.subset})`);

  if (!existsSync(outPath) || readFileSync(outPath).length === 0) {
    const res = await fetch(b.srcUrl, { headers: { "user-agent": UA } });
    if (!res.ok) throw new Error(`Font fetch failed (${res.status}) for ${b.srcUrl}`);
    writeFileSync(outPath, Buffer.from(await res.arrayBuffer()));
  }

  localBlocks.push(
    `@font-face {\n  font-family: '${b.family}';\n  font-style: ${b.style || "normal"};\n  font-weight: ${b.weight};\n  font-display: swap;\n  src: url('${localHref}') format('woff2');\n  unicode-range: ${b.unicodeRange};\n}`,
  );
}

const css = `/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n\n${localBlocks.join("\n\n")}\n`;
writeFileSync(resolve(FONT_DIR, "fonts.css"), css);
console.log(`\nWrote ${seen.size} @font-face blocks → public/fonts/fonts.css`);
