/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CafeRouteImport } from './routes/cafe'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCafeRouteImport } from './routes/admin/cafe'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminRestaurantRouteImport } from './routes/admin/restaurant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeRoute = CafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCafeRoute = AdminCafeRouteImport.update({
  id: '/admin/cafe',
  path: '/admin/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantRoute = AdminRestaurantRouteImport.update({
  id: '/admin/restaurant',
  path: '/admin/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cafe': typeof CafeRoute
  '/payment': typeof PaymentRoute
  '/restaurant': typeof RestaurantRoute
  '/admin/cafe': typeof AdminCafeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/restaurant': typeof AdminRestaurantRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cafe': typeof CafeRoute
  '/payment': typeof PaymentRoute
  '/restaurant': typeof RestaurantRoute
  '/admin/cafe': typeof AdminCafeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/restaurant': typeof AdminRestaurantRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cafe': typeof CafeRoute
  '/payment': typeof PaymentRoute
  '/restaurant': typeof RestaurantRoute
  '/admin/cafe': typeof AdminCafeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/restaurant': typeof AdminRestaurantRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cafe'
    | '/payment'
    | '/restaurant'
    | '/admin/cafe'
    | '/admin/login'
    | '/admin/restaurant'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cafe'
    | '/payment'
    | '/restaurant'
    | '/admin/cafe'
    | '/admin/login'
    | '/admin/restaurant'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/cafe'
    | '/payment'
    | '/restaurant'
    | '/admin/cafe'
    | '/admin/login'
    | '/admin/restaurant'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CafeRoute: typeof CafeRoute
  PaymentRoute: typeof PaymentRoute
  RestaurantRoute: typeof RestaurantRoute
  AdminCafeRoute: typeof AdminCafeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRestaurantRoute: typeof AdminRestaurantRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe': {
      id: '/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof CafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cafe': {
      id: '/admin/cafe'
      path: '/admin/cafe'
      fullPath: '/admin/cafe'
      preLoaderRoute: typeof AdminCafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurant': {
      id: '/admin/restaurant'
      path: '/admin/restaurant'
      fullPath: '/admin/restaurant'
      preLoaderRoute: typeof AdminRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CafeRoute: CafeRoute,
  PaymentRoute: PaymentRoute,
  RestaurantRoute: RestaurantRoute,
  AdminCafeRoute: AdminCafeRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRestaurantRoute: AdminRestaurantRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
